version: "3.8"

services:

  db:
    image: postgres
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

    # restart: always
    environment:
      POSTGRES_PASSWORD: example

volumes: 
  postgres-data:
